### ISSUE TITLE
Item create method does not work

### ISSUE THREAD

**Issue by CrokNoks** [0ctobat/octobat-php#1]
Hello,

I'll try to use your package for PHP and it's not possible to create an item with Item::create() method.

The result is a 404 error from server. This error is caused by the url that was called by the create method (/item) instead of /invoices/{id}/item.

Can you please made a correction ?

**Comment by zuuno** [comment]
Hi,
Items are a nested resource, so you need to use the following way to create them:

$invoice = \Octobat\Invoice::retrieve($invoice_id);
$invoice->items->create(...);

Does this work better?

Best,

**Comment by CrokNoks** [comment]
Well, The line you wrote didn't solve the problem, but 
```
$invoice = \Octobat\Invoice::retrieve($invoice_id);
$invoice->items()->create(...);
```
do the job.

Thank you for giving me this information
