### ISSUE TITLE
Missing SingletonApiResource.php

### ISSUE THREAD

**Issue by darthtong** [0ctobat/octobat-php#2]
Downloading `https://github.com/0ctobat/octobat-php/archive/2.0.2.zip` and integrating without using Composer fails with the error:

`require(): Failed opening required 'some-path/octobat/lib/SingletonApiResource.php'`

`SingletonApiResource.php` does not appear to exists in the repo or source archive.

**Comment by 0ctobat** [comment]
Fixed by 2.0.3 release
