### ISSUE TITLE
Bad Request

### ISSUE THREAD

**Issue by haffoudhi** [0ctobat/octobat-php#6]
I m trying \Octobat\Plaza\Account::create(
            $accountData
        );
I m getting "Bad Request" all the time, no matter what I fix.
 I already fixed phone number format and country as required by api.

$accountData = [
            'type' => 'custom',
            'email' => $email,
            'country' => $ISO3166,
            'requested_capabilities' => ['tax','invoicing'],
            'business_type' => 'company',
            'company' => [
                'name' => $societe->getRaisonSociale(),
                'address' => [
                    'city' => $adresse->getVille(),
                    'country' => $ISO3166,
                    'line1' => $line,
                    'line2' => null,
                    'zip' => $adresse->getCodePostal(),
                    'state' => null
                ],
                'phone_number' => $telephone,
                'legal' => [
                    'registration_id' => $societe->getSiret(),
                    'registry_office' => $adresseSiegeSocial,
                    'capital' => $capital
                ]
            ],
            "individual"=> [],
            'settings' => [
                'tax' => [
                    "collection"=> true,
                    'default_product_type' => 'standard',
                    'exemption_due_to_threshold' => false,
                    'vat_moss_registration' => false
                ],
                'invoicing' => [
                    'mandate' => 'standard'
                ]
            ]
        ];

**Comment by haffoudhi** [comment]
I m using test mode.

**Comment by haffoudhi** [comment]
does Octobat\Plaza\Account::create() even work?

**Comment by zuuno** [comment]
Hi,
This was not an issue with the SDK but an internal account-related backend issue.

I'm closing, sorry for the inconvenience.
